config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index' # sets the homepage to show all lists
  resources :movies, only: [:index, :show]

  resources :lists do
    resources :bookmarks 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: 'has already been added to this list' }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks # dependent: :restrict_with_error can’t delete a movie if its referenced in at least one bookmark
  has_many :lists, through: :bookmarks # A movie can be in multiple lists via bookmarks.

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list

  def new
    @bookmark = Bookmark.new
    # @movies = Movie.all
  end

  def create
    @bookmark = @list.bookmarks.new(bookmark_params)

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    list = @bookmark.list # Store the parent list before deleting the bookmark
    @bookmark.destroy
    redirect_to list_path(list), notice: "Bookmark removed!"
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  # before_action :set_list, only: [:edit, :show, :update]
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list, notice: 'List successfully created.'
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, notice: "List deleted successfully!"
  end


  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name) # include :photo?
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit class: 'btn-submit mt-3' %>
<% end %>

app/views/bookmarks/new.html.erb
<h1>Add a Movie to <%= @list.name %></h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie, collection: Movie.all, prompt: "Choose a movie" %>
  <%= f.input :comment %>
  <%= f.submit "Add Bookmark" %>
<% end %>

<%= link_to "Back to list", list_path(@list) %>

app/views/bookmarks/show.html.erb
<h2>Bookmarks</h2>
<ul>
  <% @list.bookmarks.each do |bookmark| %>
    <li>
      <%= bookmark.movie.title %> - <%= bookmark.comment %>
      <%= link_to 'Delete', [bookmark.list, bookmark], method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div>
  <h1>Movie index</h1>
</div>

<div class="container">
  <h2>Lists</h2>
  <ul>
    <% @lists.each do |list| %>
      <li>
        <%= link_to list.name, list_path(list) %>
        <%= link_to "Delete", list_path(list),

                    data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                    class: "btn btn-danger" %>
      </li>
    <% end %>
  </ul>

  <p><%= link_to "Create New List", new_list_path, class: "btn btn-primary" %></p>

  <br>
  <h2>Movies</h2>
</div>

app/views/lists/new.html.erb
<h1>Create a new list</h1>

<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :image, as: :file %> <!-- Add this for image upload -->
  <%= f.button :submit %>
<% end %>

<%= link_to "back to list", lists_path  %>

app/views/lists/show.html.erb
<div class="card mb-3" style="height: 200px; background-size: cover; background-position: center;
  background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
  url(<%= @list.image.present? ? @list.image.url : 'https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg' %>);">

  <div class="card-body text-white">
    <h1 class="card-title"><%= @list.name %></h1>
  </div>
</div>

<div class="row">
  <% @list.bookmarks.each do |bookmark| %>
    <div class="col-md-4 mb-4">
      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="<%= bookmark.movie.poster_url %>" alt="<%= bookmark.movie.title %>">
        <div class="card-body">
          <h5 class="card-title"><%= bookmark.movie.title %></h5>
          <p class="card-text"><%= bookmark.movie.overview %></p>
          <%= link_to "Go to Movie", movie_path(bookmark.movie), class: "btn btn-primary" %>
          <%= link_to "Delete Bookmark", list_bookmark_path(@list, bookmark),
            method: :delete,
            data: { confirm: "Are you sure you want to remove this bookmark?" },
            class: "btn btn-danger mt-2" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

</ul>
<%= link_to "Add a Movie", new_list_bookmark_path(@list), class: "btn btn-primary" %>
<%= link_to "Back to Lists", lists_path, class: "btn btn-secondary" %>

app/views/movies/index.html.erb
<h1>Movies#index</h1>
<ul>
  <% @movies.each do |movie|  %>
    <li>
      <img src= '<%= movie.poster_url %>' alt='<%= movie.title %>' width='100'>
     <strong><%= link_to movie.title, movie_path(movie) %></strong>
      <%= movie.rating  %>
      <%= movie.overview %>
    </li>
  <% end %>
</ul>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>
<img src="<%= @movie.poster_url %>" alt="<%= @movie.title %>" width="200">
<p>Rating: <%= @movie.rating %></p>
<p><%= @movie.overview %></p>

<%= link_to 'Back to Movies', movies_path %>